/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_demo_com_jnidemo_jni_JniUtils */

#ifndef _Included_jni_demo_com_jnidemo_jni_JniUtils
#define _Included_jni_demo_com_jnidemo_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_demo_com_jnidemo_jni_JniUtils
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_demo_com_jnidemo_jni_JniUtils_getJniString
        (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_jni_demo_com_jnidemo_jni_JniUtils_newObject
        (JNIEnv *env, jclass clazz);

JNIEXPORT jint JNICALL Java_jni_demo_com_jnidemo_jni_JniUtils_execute
        (JNIEnv *env, jclass clazz);



#ifdef __cplusplus
}
#endif
#endif
